source:
  type: cardano_net
  relay:
    - preprod-node.play.dev.cardano.org
    - 3001

sink:
  type: cardano
  db:
    type: postgres
    database_url: postgresql://carp:1234@postgres:5432/carp_preprod
  network: preprod # preview / mainnet / testnet

start_block:
