source:
  type: oura
  socket: "/node.socket" # or url
  bearer: Unix # or Tcp

sink:
  type: cardano
  db:
    type: postgres
    database_url: postgresql://carp:1234@postgres:5432/carp_preprod
  network: preprod # preview / mainnet / testnet

start_block:
